version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing .NET 8 runtime..."
      - dotnet --version

  pre_build:
    commands:
      - echo "Restoring NuGet packages..."
      - dotnet restore

  build:
    commands:
      - echo "Building project..."
      - dotnet build --configuration Release
      - echo "Publishing project..."
      - dotnet publish --configuration Release -o publish/
      - echo "Copying appspec.yml and scripts for CodeDeploy..."
      - cp appspec.yaml publish/
      - cp start_app.sh publish/

  post_build:
    commands:
      - echo "Build and packaging completed."
      - ls -la publish
      - echo "Zipping artifact for CodeDeploy..."
      - cd publish
      - zip -r ../build-artifact01.zip *
      - cd ..

artifacts:
  files:
    - build-artifact01.zip
  discard-paths: yes



