version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies..."
      - dotnet --version

  pre_build:
    commands:
      - echo "Restoring packages..."
      - dotnet restore

  build:
    commands:
      - echo "Building project..."
      - dotnet build --configuration Release
      - echo "Publishing project..."
      - dotnet publish --configuration Release -o publish/

  post_build:
    commands:
      - echo "Build & Publish completed successfully"
      - ls -la publish

artifacts:
  files:
    - '**/*'
  base-directory: publish
  discard-paths: no