version: 0.2

env:
  variables:
    S3_BUCKET: "dotnet-sampleartifactstore"   # Your S3 bucket for artifact counter
    COUNTER_FILE: "latest-build.txt"          # File to store the latest build number

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing .NET 8 runtime..."
      - dotnet --version

  pre_build:
    commands:
      - echo "Restoring NuGet packages..."
      - dotnet restore

  build:
    commands:
      - echo "Building project..."
      - dotnet build --configuration Release
      - echo "Publishing project..."
      - dotnet publish --configuration Release -o publish/
      - echo "Copying appspec.yml and scripts for CodeDeploy..."
      - cp appspec.yaml publish/
      - cp start_app.sh publish/
      - echo "Fetching last build number from S3..."
      - 'LATEST=$(aws s3 ls s3://$S3_BUCKET/$COUNTER_FILE && aws s3 cp s3://$S3_BUCKET/$COUNTER_FILE - || echo 0)'
      - 'BUILD_NUM=$(printf "%02d" $((LATEST + 1)))'
      - echo "New build artifact: $ARTIFACT_NAME"
      - cd publish
      - zip -r "../$ARTIFACT_NAME" *
      - cd ..
      - echo $BUILD_NUM | aws s3 cp - s3://$S3_BUCKET/$COUNTER_FILE


  post_build:
    commands:
      - echo "Build and packaging completed."
      - ls -la publish

artifacts:
  files:
    - "build-*.zip"
  discard-paths: yes


